package com.github.knoweth.server.storage;

import com.github.knoweth.common.data.Document;
import org.springframework.data.repository.CrudRepository;

import java.util.List;

/**
 * CRUD repository interface that stores Documents.
 * <p>
 * Implementation auto-generated by Spring.
 *
 * @author Kevin Liu
 */
public interface DocumentRepository extends CrudRepository<Document, Long> {
    List<Document> findByAuthor(String author);
}
